name: Destroy Environment

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_region: ${{ vars.AWS_REGION }}
  TF_VAR_environment: dev
  TF_VAR_base_reference: chrispsheehan-lambda-ssr-react

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-region: ${{ vars.AWS_REGION }}
            role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ROLE }}
            role-session-name: GitHubActions

      - name: destroy cdn
        shell: bash
        run: |
          cd tf/cdn
          terraform init
          terraform destroy -auto-approve

      - name: destroy ssr
        shell: bash
        run: |
          cd tf/ssr
          terraform init
          terraform destroy -auto-approve --var lambda_zip_path=/no.zip -var static_files_source=blh.com
