name: Destroy Environment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_region: ${{ vars.AWS_REGION }}
  TF_VAR_environment: dev
  TF_VAR_base_reference: chrispsheehan-lambda-ssr-react

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-region: ${{ vars.AWS_REGION }}
            role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.AWS_ROLE }}
            role-session-name: GitHubActions

      - name: init
        shell: bash
        run: |
          cd tf
          terraform init

      - name: destroy
        shell: bash
        run: |
          cd tf
          terraform destroy -auto-approve --var lambda_zip_path=/no.zip
